# Generated by Django 4.2.5 on 2025-07-06 14:06

from django.db import migrations, models
import django.db.models.deletion
import mln.models.static.static


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0033_networkerreply_trigger_item_obtained_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSetupCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('item', models.ForeignKey(limit_choices_to={'type': mln.models.static.static.ItemType['ITEM']}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_codemodule', to='mln.module')),
            ],
        ),
    ]
